package io.flutter.plugins;

import androidx.annotation.Keep;
import androidx.annotation.NonNull;

import io.flutter.embedding.engine.FlutterEngine;

/**
 * Generated file. Do not edit.
 * This file is generated by the Flutter tool based on the
 * plugins that support the Android platform.
 */
@Keep
public final class GeneratedPluginRegistrant {
  public static void registerWith(@NonNull FlutterEngine flutterEngine) {
    flutterEngine.getPlugins().add(new fr.freekit.FlutterVolumeSlider.FlutterVolumePlugin());
    flutterEngine.getPlugins().add(new com.example.systemshortcuts.SystemShortcutsPlugin());
    flutterEngine.getPlugins().add(new com.example.volume.VolumePlugin());
    flutterEngine.getPlugins().add(new com.weyiyong.plugins.volume_control.VolumeControlPlugin());
  }
}
